# Typically, you would not share this file as it contains sensitive information.
# However, for the purposes of this app, we are including the database connection string here for convenience.
# Remember, the current intention of this app is for self-hosting and local use only.
[connections.streamlit_ollama_db]
url = "sqlite:///data/streamlit-ollama.db"